import type { IBudgetService } from "../../domain/models/application/interface/BudgetService.js";
import { LogService } from "../../services/systemLogService.js";

export class BudgetController {
  constructor(private budgetService: IBudgetService) {}

  getBudgets = async (req: any, res: any) => {
    try {
      const userId = req.user.id;
      const {  month, year } = req.query;

      if (!userId || !month || !year) { 
        return res.status(400).json({ message: 'userId, month, year là bắt buộc' });
      }

      const result = await this.budgetService.getBudgets({ userId, month, year });

      return res.status(200).json(result);
    } catch (error:any) {
        await LogService.write({
        message: `getBudgets error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.get.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('getBudgets error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  }; 

  createBudget = async (req: any, res: any) => {
    try {
      const userId = req.user.id;
      const {  categoryId, target, date, status } = req.body;

      console.log( userId, categoryId, target, date, status )

      if (!userId || !categoryId || !target || !date) {
        return res.status(400).json({ message: 'Thiếu thông tin bắt buộc' });
      }

      const result = await this.budgetService.createBudget({
        userId,
        categoryId,
        target,
        date,
        status: status ?? 'active',
      });

      if (!result) {
        return res.status(409).json({ message: 'Budget cho category này đã tồn tại trong tháng' });
      }

      return res.status(201).json(result);
    } catch (error:any) {
        await LogService.write({
        message: `createBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.create.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('createBudget error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  };

  updateBudget = async (req: any, res: any) => {
    try {
      const userId = req.user.id;
      const { id: budgetId } = req.params;
      const {  target } = req.body;

      if (!budgetId || !userId || !target) {
        return res.status(400).json({ message: 'Thiếu thông tin bắt buộc' });
      }

      console.log( userId, budgetId, target)

      const result = await this.budgetService.updateBudget({ userId, budgetId, target });

      if (!result) {
        return res.status(404).json({ message: 'Budget không tồn tại hoặc không có quyền' });
      }

      return res.status(200).json(result);
    } catch (error:any) {
      await LogService.write({
        message: `deleteBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.delete.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('updateBudget error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  };

  deleteBudget = async (req: any, res: any) => {
    try {
      const { id: budgetId } = req.params;
      const userId = req.user.id;

      if (!budgetId || !userId) {
        return res.status(400).json({ message: 'Thiếu thông tin bắt buộc' });
      }

      const result = await this.budgetService.deleteBudget({ userId, budgetId });

      if (!result) {
        return res.status(404).json({ message: 'Budget không tồn tại hoặc không có quyền' });
      }

      return res.status(200).json(result);
    } catch (error:any) {
      await LogService.write({
        message: `chatController error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'ai.chat.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('deleteBudget error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  };

  getAutoGeneratedBudget = async (req: any, res: any) => {
    try {
      // const userId = req.user.id;
      const { month, year, userId } = req.query;
      if (!userId || !month || !year) {
        return res.status(400).json({ message: 'userId, month, year là bắt buộc' });
      }
      const result = await this.budgetService.getAutoGeneratedBudget(userId, month, year );

      return res.status(200).json(result);
    } catch (error:any) {
      await LogService.write({
        message: `getAutoGeneratedBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.autoGenerate.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('getAutoGeneratedBudget error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  };

  generateBudget =async (req: any, res: any)=> {
    try {
      const userId = req.user.id;
      const { budgets, transactions, categories, wallets } = req.body;

      console.log('================ DATA FOR AUTO BUDGET ================');
      console.log('UserId:', userId);
      console.log('Budgets:', budgets);
      console.log('Transactions:', transactions);
      console.log('Categories:', categories);
      console.log('Wallets:', wallets);

      const result = await this.budgetService.autoGenerateBudget(userId, budgets, transactions, categories, wallets);

      return res.status(200).json(result);

    } catch (error:any) {
      await LogService.write({
        message: `autoGenerateBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.autoGenerate.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('autoGenerateBudget error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  }

  addMultipleBudget = async (req: any, res: any) => {
    try {
      const userId = req.user.id;
      const { budgets } = req.body;

      console.log('================ ADD MULTIPLE BUDGET ================');
      console.log('UserId:', userId);
      console.log('Budgets:', budgets);

      const result = await this.budgetService.addMultipleBudget(userId, budgets);

      return res.status(200).json(result);

    } catch (error:any) {
        await LogService.write({
        message: `createBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.create.error',
        actorId: req.user?.id, ipAddress: req.ip,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('createBudget error:', error);
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  };  
}

// Budgets: [
//   {
//     categoryId: 'a1b2c3d4-0002-4000-8000-000000000002',
//     target: '{"ciphertext":"fJpXBvxNgg==","iv":"DHSIqZlC4VotrJk6","tag":"Oh0kgnZp8lM5G0jSkYGezg=="}',
//     date: '03/2026',
//     status: 'active'
//   },
//   {
//     categoryId: 'a1b2c3d4-0001-4000-8000-000000000001',
//     target: '{"ciphertext":"V0DbmQ8G","iv":"ipz8jmn6fJhGB55r","tag":"r3T0fYZ/Tc4TkOX68NjKQg=="}',
//     date: '03/2026',
//     status: 'active'
//   }
// ]