import { ITransaction } from "../../models/IApp";

const mockSending:ITransaction[]= [
  {
    id: '1',
    category: { id: '1', name: 'Dining', iconName: 'restaurant', type:"sending", iconColor: "240, 40, 0" },
    amount: '-150000',
    type: 'sending',
    wallet: 'Main Wallet',
    date: '2026-02-12',
    note: '',
    buget: 'Dining',
    title: 'Lunch with client',
  },
  {
    id: '3',
    category: { id: '3', name: 'Transport', iconName: 'directions-car', type:"sending", iconColor:"240, 160, 0" },
    amount: '-50000',
    type: 'sending',
    wallet: 'Main Wallet',
    date: '2026-02-11',
    note: '',
    buget: 'Transport',
    title: 'Taxi home',
  },
  {
    id: '4',
    category: { id:'4', name: 'Shopping', iconName: 'shopping-cart', type:"sending", iconColor: "224, 240, 0" },
    amount: '-500000',
    type: 'sending',
    wallet: 'Credit Card',
    date: '2026-02-09',
    note: '',
    buget: 'Entertainment',
    title: 'Buy new clothes',
  },
  {
    id: '5',
    category: { id: '5', name: 'Education', iconName: 'school', type:"sending", iconColor: "112, 240, 0" },
    amount: '-1200000',
    type: 'sending',
    wallet: 'Main Wallet',
    date: '2026-02-05',
    note: '',
    buget: 'Development',
    title: 'React Native Course',
  },
  {
    id: '6',
    category: { id: '6', name: 'Entertainment', iconName: 'movie', type:"sending", iconColor: "0, 240, 144" },
    amount: '-100000',
    type: 'sending',
    wallet: 'Main Wallet',
    date: '2026-02-08',
    note: '',
    buget: 'Entertainment',
    title: 'Movie ticket',
  },
  {
    id: '7',
    category: { id: '1', name: 'Dining', iconName: 'restaurant', type:"sending", iconColor: "0, 240, 240" },
    amount: '-75000',
    type: 'sending',
    wallet: 'Main Wallet',
    date: '2026-02-12',
    note: '',
    buget: 'Dining',
    title: 'Morning coffee',
  },
  {
    id: '8',
    category: { id: '7', name: 'Health', iconName: 'fitness-center', type:"sending", iconColor: "0, 132, 240" },
    amount: '-300000',
    type: 'sending',
    wallet: 'Bank Account',
    date: '2026-02-07',
    note: '',
    buget: 'Health',
    title: 'Gym fee for March',
  },
  {
    id: '9',
    category: { id: '8', name: 'Electricity', iconName: 'bolt', type:"sending", iconColor: "172, 0, 240" },
    amount:' -850000',
    type: 'sending',
    wallet: 'Bank Account',
    date: '2026-02-02',
    note: '',
    buget: 'Living',
    title: 'Electricity payment',
  }
];

const mockIncome = [
  {
    id: '2',
    category: { id: '2', name: 'Salary', iconName: 'work', type:"income", iconColor: "240, 0, 160" },
    amount: '15000000',
    type: 'income',
    wallet: 'Bank Account',
    date: '2026-02-10',
    note: '',
    buget: 'Uncategorized',
    title: 'Salary for February',
  },
  {
    id: '10',
    category: { id: '9', name: 'Sales', iconName: 'attach-money', type:"income", iconColor: "100, 116, 139" },
    amount: '2000000',
    type: 'income',
    wallet: 'Bank Account',
    date: '2026-02-04',
    note: '',
    buget: 'Uncategorized',
    title: 'Sell old laptop',
  },
]

export {mockIncome, mockSending};