import { ITransaction } from "../../models/IApp";

const mockSending:ITransaction[]= [
  {
    id: '1',
    category: { id: '1', name: 'Ăn uống', iconName: 'restaurant', type:"sending", iconColor: "240, 40, 0" },
    amount: '-150000',
    type: 'sending',
    wallet: 'Ví chính',
    date: '2026-02-12',
    note: '',
    buget: 'Ăn uống',
    title: 'Ăn trưa với khách hàng',
  },
  {
    id: '3',
    category: { id: '3', name: 'Di chuyển', iconName: 'directions-car', type:"sending", iconColor:"240, 160, 0" },
    amount: '-50000',
    type: 'sending',
    wallet: 'Ví chính',
    date: '2026-02-11',
    note: '',
    buget: 'Di chuyển',
    title: 'Taxi về nhà',
  },
  {
    id: '4',
    category: { id:'4', name: 'Mua sắm', iconName: 'shopping-cart', type:"sending", iconColor: "224, 240, 0" },
    amount: '-500000',
    type: 'sending',
    wallet: 'Thẻ tín dụng',
    date: '2026-02-09',
    note: '',
    buget: 'Giải trí',
    title: 'Mua quần áo mới',
  },
  {
    id: '5',
    category: { id: '5', name: 'Học tập', iconName: 'school', type:"sending", iconColor: "112, 240, 0" },
    amount: '-1200000',
    type: 'sending',
    wallet: 'Ví chính',
    date: '2026-02-05',
    note: '',
    buget: 'Phát triển',
    title: 'Khóa học React Native',
  },
  {
    id: '6',
    category: { id: '6', name: 'Giải trí', iconName: 'movie', type:"sending", iconColor: "0, 240, 144" },
    amount: '-100000',
    type: 'sending',
    wallet: 'Ví chính',
    date: '2026-02-08',
    note: '',
    buget: 'Giải trí',
    title: 'Vé xem phim',
  },
  {
    id: '7',
    category: { id: '1', name: 'Ăn uống', iconName: 'restaurant', type:"sending", iconColor: "0, 240, 240" },
    amount: '-75000',
    type: 'sending',
    wallet: 'Ví chính',
    date: '2026-02-12',
    note: '',
    buget: 'Ăn uống',
    title: 'Cà phê sáng',
  },
  {
    id: '8',
    category: { id: '7', name: 'Sức khỏe', iconName: 'fitness-center', type:"sending", iconColor: "0, 132, 240" },
    amount: '-300000',
    type: 'sending',
    wallet: 'Tài khoản ngân hàng',
    date: '2026-02-07',
    note: '',
    buget: 'Sức khỏe',
    title: 'Phí tập gym tháng 3',
  },
  {
    id: '9',
    category: { id: '8', name: 'Tiền điện', iconName: 'bolt', type:"sending", iconColor: "172, 0, 240" },
    amount:' -850000',
    type: 'sending',
    wallet: 'Tài khoản ngân hàng',
    date: '2026-02-02',
    note: '',
    buget: 'Sinh hoạt',
    title: 'Thanh toán tiền điện',
  }
];

const mockIncome = [
  {
    id: '2',
    category: { id: '2', name: 'Lương', iconName: 'work', type:"income", iconColor: "240, 0, 160" },
    amount: '15000000',
    type: 'income',
    wallet: 'Tài khoản ngân hàng',
    date: '2026-02-10',
    note: '',
    buget: 'Chưa phân loại',
    title: 'Lương tháng 2',
  },
  {
    id: '10',
    category: { id: '9', name: 'Bán hàng', iconName: 'attach-money', type:"income", iconColor: "100, 116, 139" },
    amount: '2000000',
    type: 'income',
    wallet: 'Tài khoản ngân hàng',
    date: '2026-02-04',
    note: '',
    buget: 'Chưa phân loại',
    title: 'Bán laptop cũ',
  },
]

export {mockIncome, mockSending};