export const COUNTRY_FLAG_MAP: Record<string, string> = {
  'Mỹ': 'US',
  'Nhật bản': 'JP',
  'Nga': 'RU',
  'Singapo': 'SG',
  'Lào': 'LA',
  'Trung Quốc': 'CN',
  'Hồng Kông': 'HK',
  'Philipinh': 'PH',
  'Campuchia': 'KH',
  'Malaysia': 'MY',
  'Ấn độ': 'IN',
  'Thái lan': 'TH',
  'Hàn quốc': 'KR',
  'New Zealand': 'NZ',
  'Úc': 'AU',
  'Canada': 'CA',
  'Hà lan': 'NL',
  'Vương quốc Anh': 'GB',
  'Euro': 'EU',
  'Na uy': 'NO',
  'Barazil': 'BR',
  'Thụy Điển': 'SE',
  'Thụy sĩ': 'CH',
  'Tiểu vương quốc Ả Rập Thống Nhất': 'AE',
  'Nam Phi': 'ZA',
};