import type { IBudgetService } from "../../domain/models/application/interface/BudgetService.js";
import type { IBudgetRepository } from "../../domain/models/application/repository/IBudgetRepo.js";
import type { GetBudgetsDTO, CreateBudgetDTO, UpdateBudgetDTO, DeleteBudgetDTO } from "../../data/DTO/AppDTO.js";
import type { BudgetEntity,DataForAI, CategoryEntity, WalletEntity } from "../../domain/entities/appEntities.js";
import { LogService } from "../systemLogService.js";
import pool from "../../config/dbConfig.js";
import { CategoryRepository } from "../../data/repositories/CategoryRepository.js";
import { TransactionRepository } from "../../data/repositories/TransactionRepository.js";
import type { TransactionForGemini } from "../../data/DTO/AppDTO.js";
import { usageStatsRepository } from "../../data/repositories/usageStatsRepoImpl.js";
import { budgetPrompt } from "../../AI/budget.prompt.js";
import { callGemini } from "../chatService/LLMService.js";

export interface GeminiBudgetResponse {
  message: string;
  budgets: {
    categoryId: string;
    categoryName: string;
    iconName: string;
    iconColor: string;
    categoryType:string;
    target: string;
    date: string;
  }[]
}

export class BudgetService implements IBudgetService {
  private _categoryRepo = new CategoryRepository(pool)
  private _transactionRepo = new TransactionRepository(pool)

  constructor(private budgetRepo: IBudgetRepository) {}

  async getBudgets(dto: GetBudgetsDTO): Promise<BudgetEntity[]> {
    try {
      return await this.budgetRepo.findByMonth(dto);
    } catch (error: any) {
      await LogService.write({
        message: `getBudgets error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.get.service_error',
        actorId: dto.userId,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('getBudgets error:', error);
      return [];
    }
  }

  async createBudget(dto: CreateBudgetDTO): Promise<boolean> {
    try {
      const [month, year] = dto.date.split('/');
      const yearMonth = `${year}-${month}-01`;
      const isDuplicate = await this.budgetRepo.findDuplicate(dto.userId, dto.categoryId, yearMonth);
      if (isDuplicate) {
        console.warn(`Budget đã tồn tại: category ${dto.categoryId} tháng ${yearMonth}`);
        return false;
      }
      return await this.budgetRepo.create(dto);
    } catch (error: any) {
      await LogService.write({
        message: `createBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.create.service_error',
        actorId: dto.userId,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('createBudget at service error:', error);
      return false;
    }
  }

  async updateBudget(dto: UpdateBudgetDTO): Promise<boolean> {
    try {
      return await this.budgetRepo.update(dto);
    } catch (error: any) {
      await LogService.write({
        message: `updateBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.update.service_error',
        actorId: dto.userId,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('updateBudget error:', error);
      return false;
    }
  }

  async deleteBudget(dto: DeleteBudgetDTO): Promise<boolean> {
    try {
      return await this.budgetRepo.delete(dto);
    } catch (error: any) {
      await LogService.write({
        message: `deleteBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.delete.service_error',
        actorId: dto.userId,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('deleteBudget error:', error);
      return false;
    }
  }

  async getAutoGeneratedBudget(userId:string, month:string, year:string ):Promise<DataForAI>{
    try {
      const endDate = new Date(parseInt(year), parseInt(month), 0).toISOString().split('T')[0] as string;
      // Ngày đầu tiên của 2 tháng trước
      const startDate = new Date(parseInt(year), parseInt(month) - 3, 1).toISOString().split('T')[0] as string;

      const categories = await this._categoryRepo.getAllCategory(userId);
      const budgets = await this.budgetRepo.findByMonth({userId, month, year}, {start:startDate, end:endDate});
      const transactions = await this._transactionRepo.find(userId, {endDate:endDate, startDate:startDate});

      return { buget: budgets, category: categories, transaction: transactions };
    } catch (error:any) {
      await LogService.write({
        message: `getAutoGeneratedBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.get.service_error',
        actorId: userId,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('getAutoGeneratedBudget error:', error);
      return {buget:[], category:[], transaction:[]};
    }
  }

  async autoGenerateBudget(userId:string, budgets: BudgetEntity[] | null, transactions: TransactionForGemini[] | null, 
      categories: CategoryEntity[] | null, wallets: WalletEntity[] | null):Promise<GeminiBudgetResponse> {
      try {
        const thisMonth = new Date().getMonth() + 1;
        const thisYear = new Date().getFullYear();

        usageStatsRepository.incrementPrompt().catch((err) => console.error(err));

        const buildBudgetPrompt = budgetPrompt(`${thisYear}-${thisMonth}`, budgets, transactions, categories, wallets);

        const response = await callGemini('budget', { systemPrompt: buildBudgetPrompt, tools: [], message: '' });

        return response as GeminiBudgetResponse;
      } catch (error:any) {
        if (error.actionDetail !== 'ai.gemini.call.failed') {
          await LogService.write({
            message: `autoGenerateBudget service unexpected error: ${error.message}`,
            actor_type: 'system',
            type: 'error',
            status: 'failure',
            actionDetail: 'ai.budget.service.error',
            actorId: userId,
            metaData: { error: error.message, stack: error.stack } as any,
          });
        }
        throw error;
      }
  }

  async  addMultipleBudget(userId:string, budgets: any[]): Promise<boolean>{
    try {      
      return await this.budgetRepo.createMultiple( userId, budgets );
    } catch (error:any) {
      await LogService.write({
        message: `addMultipleBudget error: ${error.message}`,
        actor_type: 'system', type: 'error', status: 'failure',
        actionDetail: 'budget.addMultiple.service_error',
        actorId: userId,
        metaData: { error: error.message, stack: error.stack } as any,
      });
      console.error('addMultipleBudget error:', error);
      return false;
    }
  }
}