import type{ BudgetEntity, DataForAI, CategoryEntity,WalletEntity } from "../../../entities/appEntities.js";
import type { CreateBudgetDTO, GetBudgetsDTO, UpdateBudgetDTO, DeleteBudgetDTO, TransactionForGemini } from "../../../../data/DTO/AppDTO.js";
import type { GeminiBudgetResponse } from "../../../../services/applicationService/BudgetService.js";

export interface IBudgetService {
  getBudgets(dto: GetBudgetsDTO): Promise<BudgetEntity[]>;
  createBudget(dto: CreateBudgetDTO): Promise<boolean>;
  updateBudget(dto: UpdateBudgetDTO): Promise<boolean>;
  deleteBudget(dto: DeleteBudgetDTO): Promise<boolean>;
  getAutoGeneratedBudget(userId:string, month:string, year:string ):Promise<DataForAI>;
  autoGenerateBudget(userId:string, budgets: BudgetEntity[] | null, transactions: TransactionForGemini[] | null, 
    categories: CategoryEntity[] | null, wallets: WalletEntity[] | null): Promise<GeminiBudgetResponse>;
  addMultipleBudget(userId:string, budgets: any[]): Promise<boolean>;
}